# Model Paths
# teacher_model_path: "./models/gpt2-medium-wikitext"
# student_model_name: "gpt2"
# base_model_name: "gpt2-medium"
# save_path: "./models/gpt2-distilled-bayeslearner"


# # Colab Model Paths
teacher_model_path: "/content/distill_llm/models/gpt2-medium-wikitext"
student_model_name: "gpt2"
base_model_name: "gpt2-medium"
save_path: "/content/distill_llm/models/gpt2-distilled-bayeslearner"


# Training Hyperparameters
training:
  learning_rate: 5.0e-5
  batch_size: 8
  gradient_accumulation_steps: 4
  epochs: 2
  fp16: true
  temperature: 2.0
  alpha: 0.5

# SGLD Specifics
sgld:
  burn_in_steps: 3000
  precondition_decay: 0.95

# Dataset
dataset:
  name: "wikitext"
  subset: "wikitext-2-raw-v1"
  max_length: 512

# Weight Collection Settings
sampling:
  enabled: false
  start_step: 4000
  end_step: 10000
  interval: 500
  save_dir: "./model_samples"

# SWAG Specific Settings
swag:
  enabled: true
  max_num_models: 20
  start_step: 2000
  interval: 50
  scale: 1.0